export const palabrasClave = [
    "Monitoreo parental",
    "Control parental",
    "Aplicación de monitoreo silencioso",
    "Grooming",
    "Espiar",
    "Espiar Teléfono",
    "Espiar Celular",
    "Aplicación para espiar celular",
    "Teléfono Espía",
    "Infidelidad",
    "Pareja",
    "Espiar Pareja",
    "Elite",
    "Aplicación Elite",
    "Protección infantil en línea",
    "Seguridad en línea para niños",
    "Control de actividades en línea",
    "Aplicación de rastreo GPS",
    "Rastreo",
    "Rastreo Celular",
    "Monitoreo de mensajes",
    "Monitoreo de llamadas",
    "Bloqueo de aplicaciones",
    "Control de pantalla",
    "Control de tiempo de pantalla",
    "Monitoreo de redes sociales",
    "Espiar Whatsapp",
    "Espiar Chats",
    "Monitorear Chats",
    "Seguridad",
    "GPS",
    "Aplicación Cámara Espía",
    "Cámara Espía Celular",
    "Cámara Espía",
    "como monitorear un celular",
    "aplicacion para rastrear celular",
    "monitoreo de celular",
    "rastrear un celular",
    "app para espiar celular",
    "ubicacion de celular por numero",
    "localizacion celular",
    "localizar celular con numero de telefono",
    "localizar dispositivo movil",
    "localizar ubicacion telefono",
    "rastrear telefono movil",
    "app control",
    "mejor control parental",
    "app para espiar con quien habla por whatsapp",
    "ubicar telefono",
    "aplicaciones de control parental gratis",
    "ubicar por gps",
    "rastrear numero movil",
    "app control parental gratis",
    "software para espiar whatsapp",
    "monitorear movil",
    "para localizar un movil",
    "buscar celular",
    "ubicación en tiempo real celular",
    "gps celular",
    "control parental celular",
    "localizar un movil",
    "app para espiar",
    "aplicaciones control parental",
    "control de acceso por celular",
    "gps localizar celular",
    "ubicacion de movil por numero",
    "rastrear celular por el numero",
    "app espia whatsapp",
    "software para whatsapp",
    "hackear el whatsapp",
    "localizacion de numero telefonico",
    "app para control parental",
    "aplicaciones para control parental gratis",
    "rastreo de celulares gratis",
    "rastreo de un numero celular",
    "ubicar telefono movil",
    "monitorear celular",
    "localizacion de un telefono movil",
    "aplicación para monitorear un celular",
    "aplicaciones para control parental",
    "aplicacion gratis para rastrear celular",
    "rastrear telefono celular",
    "rastrear telefono con numero",
    "rastrear un celular por numero",
    "android control parental",
    "app para whatsapp",
    "app para ver whatsapp",
    "seguimiento gps para movil",
    "ubicación de celular en tiempo real",
    "whatsapp espia",
    "ubicacion de un telefono movil",
    "localizar celular por numero de telefono",
    "localizar un celular por numero",
    "ubicacion telefono celular",
    "puedo rastrear un numero de celular",
    "encontrar localizacion de un celular",
    "espia de whatsapp",
    "mensajes de celular",
    "control parental gratis",
    "ubicación de teléfono",
    "ubicacion de celular",
    "localizar mi dispositivo",
    "app para monitorear celular",
    "buscar mi telefono",
    "aplicación para seguir un celular",
    "ubicacion de telefono celular",
    "parental software",
    "para whatsapp",
    "ubicar un telefono",
    "ubicar celular por el numero",
    "app para whatsapp para ver con quién habla",
    "rastreo gps celular",
    "aplicaciones para whatsapp",
    "rastrear movil por numero",
    "rastrear celular con numero de telefono",
    "se puede localizar un celular por el numero",
    "ubicar movil por numero",
    "se puede rastrear un movil",
    "para hackear whatsapp",
    "rastreo de telefono celular",
    "rastrear celular por numero de telefono",
    "programa espia whatsapp",
    "control de padres en celulares",
    "aplicacion para rastrear a una persona",
    "app de control parental",
    "encontrar ubicacion con numero de celular",
    "localizar celular por gps",
    "rastrear un número de teléfono",
    "aplicación para whatsapp",
    "rastreo de numero de celular",
    "fotos de celulares",
    "localizar telefono movil",
    "rastrear ubicacion de celular gratis",
    "rastrear ubicacion de celular por numero",
    "rastrear un celular con el numero",
    "app espiar celular",
    "rastrear celular con numero de celular",
    "buscar mi movil",
    "aplicaciones para monitorear celulares",
    "app para seguir un celular",
    "buscar mi dispositivo",
    "gps para encontrar celular",
    "ubicar numero de telefono",
    "app control parental",
    "rastrear mi telefono",
    "ubicacion de un celular",
    "control de acceso con celular",
    "ubicar mi dispositivo",
    "localizar mi movil",
    "app para monitorear celular gratis",
    "se puede localizar un movil",
    "rastrear numero de movil",
    "para ubicar un celular",
    "rastrear persona por celular",
    "aplicaciones control parental gratis",
    "rastrear ubicacion con numero de celular",
    "rastrear un telefono por el numero",
    "aplicaciones de control parental",
    "seguir celular por gps",
    "rastrear celular por gps",
    "ubicar numero telefonico",
    "buscar ubicacion de un telefono movil",
    "app para rastrear celular gratis",
    "rastrear ubicacion de un movil",
    "ubicar mi dispositivo movil",
    "localizar un celular por su numero",
    "localizar un telefono por el numero",
    "saber la ubicación de un móvil",
    "localizar por movil",
    "app control parental whatsapp",
    "control app",
    "rastrear un celular por el numero",
    "localizar gps de celular",
    "control parental whatsapp",
    "rastrear ubicacion movil",
    "rastrear ubicación de teléfono",
    "localización de número de teléfono",
    "Gps",
    "Aplicacion Camara Espia",
    "Camara Espia Celular",
    "Camara Espia"
]

export function palabrasClaveConcatenadas() {
    if (palabrasClave.length === 0) {
      return "";
    }
    return palabrasClave.join(", ");
  }